const FANCY_INDEX_SORT = {
  COLUMN_FILE_NAME: 'N',
  COLUMN_FILE_SIZE: 'S',
  COLUMN_MODIFY_DATE: 'M',
  ORDER_ASC: 'A',
  ORDER_DESC: 'D',

  KEY_COLUMN: 'C',
  KEY_ORDER: 'O',
};

module.exports = {
  FANCY_INDEX_SORT,
};
